import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/Header";
import LogoBanner from "../components/LogoBanner";
import ConsentOrdersInAustralia from "../content/ConsentOrdersInAustralia";
import ContactUs from "../content/ContactUs";
import FreeDiscussion from "../content/FreeDiscussion";
import MKITeam from "../content/MKITeam";
import MostOnlinePopularServices from "../content/MostOnlinePopularServices";
import OurLegalTeam from "../content/OurLegalTeam";
import SendAnOfferToYourEx from "../content/SendAnOfferToYourEx";
import WeOperateAustraliaWide from "../content/WeOperateAustraliaWide";
import WeWillRepresentYou from "../content/WeWillRepresentYou";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-auto relative">
        <Header />
        <FreeDiscussion/>
        <MostOnlinePopularServices/>
        <MKITeam/>
        <ConsentOrdersInAustralia/>
        <LogoBanner/>
        <SendAnOfferToYourEx/>
        <WeWillRepresentYou/>
        <OurLegalTeam />
        <WeOperateAustraliaWide />
        <ContactUs/>
      </main>

      <Footer />
    </div>
  );
}
