import Head from "next/head";
import LogoBanner from "../components/LogoBanner";
import ConsentOrdersInAustralia from "../content/ConsentOrdersInAustralia";
import FreeDiscussion from "../content/FreeDiscussion";
import MKITeam from "../content/MKITeam";
import MostOnlinePopularServices from "../content/MostOnlinePopularServices";
import OurLegalTeam from "../content/OurLegalTeam";
import SendAnOfferToYourEx from "../content/SendAnOfferToYourEx";
import WeOperateAustraliaWide from "../content/WeOperateAustraliaWide";
import WeWillRepresentYou from "../content/WeWillRepresentYou";

import DefaultLayout from "layouts/BaseLayout";
import GetInTouch from "components/GetInTouch";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <FreeDiscussion />
        <MostOnlinePopularServices />
        <MKITeam />
        <ConsentOrdersInAustralia />
        <LogoBanner />
        <SendAnOfferToYourEx />
        <WeWillRepresentYou />
        <OurLegalTeam />
        <WeOperateAustraliaWide />
        <GetInTouch isDiscussionFreeToShow={true} />
      </DefaultLayout>
    </div>
  );
}
